---
title: "CESA_KO_Enrichment"
author: "Kerrina Whelan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

# Load required packages
library(tidyverse)
library(patchwork)  # For layout
library(RColorBrewer)
library(viridis)  # Optional for plotting

knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

---


```{r load-data, include=FALSE}

# Define file paths for DEGs, Phytozome annotations, and Pfam domain descriptions
deg_path <- "data/Significant-DEGs_WT-vs-KO1.csv"
anno_path <- "data/phytozome_annotation.txt"
pfam_path <- "data/pfamA.txt"

# Load data
degs <- read_csv(deg_path)
anno <- read_tsv(anno_path)

# Read in the PANTHER analysis tables and KEGG chart (from DAVID)
bp <- read.delim("data/PANTHER_bp_analysis_table.txt", skip = 11, header = TRUE, sep = "\t")
mf <- read.delim("data/PANTHER_mf_analysis_table.txt", skip = 11, header = TRUE, sep = "\t")
cc <- read.delim("data/PANTHER_cc_analysis_table.txt", skip = 11, header = TRUE, sep = "\t")
kegg <- read.delim("data/KEGG_functional_annotation_chart.txt", header = TRUE, sep = "\t", quote = "")


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
